#include "stdafx.h"
#include "math.h"

#include "Point3D.h"
#include "Command.h"


#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

//show a circle
void CCommand::ShowCpaturePoint(const CPoint3D &pos, BOOL bShow /* = FALSE */)
{

}


BOOL CCommand::GetNearKeyPoint(CPoint3D &pt)
{

	return FALSE;
}
//
int CCommand::OnMouseMove(UINT nFlags, const CPoint3D& pos)
{


	return 0;
}
